name: CI

on:
  push:
    branches: [main, GH_ActionsTestBranch]
  pull_request:

permissions:
  contents: read

jobs:
  playwright-test:
    uses: ./.github/workflows/reusable-base.yml
    with:
      build-script: npx playwright install chromium
      setup-build-cache: true
      test-script: e2e:ci
      upload-name: playwright-report
      upload-path: playwright-report/
